openapi: 3.0.3
info:
  title: Interoperability API Gateway Micro Service
  description: defines the persistence operations for the agreement
  version: '0.0.1'
  contact:
    name: API Support
    url: 'http://www.example.com/support'
    email: support@example.com
  termsOfService: 'http://swagger.io/terms/'
  x-api-id: an x-api-id
  x-summary: an x-summary
servers:
  - url: 'https://interop.pagopa.it/interop-api-gateway/0.0.1'
    description: This service is the interoperability api gateway
tags:
  - name: api
    description: Everything about your APIs
    externalDocs:
      description: Find out more
      url: 'http://swagger.io'
security:
  - bearerAuth: [ ]
paths:
  '/agreements/{agreementId}':
    get:
      tags:
        - api
      summary: Get an agreement
      description: Retrieve an agreement using an agreement identifier
      operationId: getAgreement
      security:
        - bearerAuth: [ ]
      parameters:
        - name: agreementId
          in: path
          description: the agreement id
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: Agreement retrieved
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Agreement'
        '400':
          description: Bad request
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/Problem'
        '404':
          description: Agreement not found
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/Problem'
  '/purposes/{purposeId}':
    get:
      tags:
        - api
      summary: Get an purpose
      description: Retrieve a purpose using a purpose identifier
      operationId: getPurpose
      parameters:
        - name: purposeId
          in: path
          description: the purpose Id
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Purpose retrieved
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Purpose'
        '400':
          description: Bad request
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/Problem'
        '404':
          description: Purpose not found
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/Problem'
  '/purposes/{purposeId}/agreement':
    get:
      tags:
        - api
      summary: Get an agreement by purposeId
      description: Retrieve the agreement associated to a purpose
      operationId: getAgreementByPurpose
      security:
        - bearerAuth: [ ]
      parameters:
        - name: purposeId
          in: path
          description: the purpose Id
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Agreement retrieved
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Agreement'
        '400':
          description: Bad request
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/Problem'
        '404':
          description: Agreement not found
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/Problem'
  '/attribute/{attributeId}':
    get:
      tags:
        - api
      summary: Get an attribute
      description: Retrieve an attribute using an attribute identifier
      operationId: getAttribute
      security:
        - bearerAuth: [ ]
      parameters:
        - name: attributeId
          in: path
          description: the attribute Id
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Attribute retrieved
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Attribute'
        '400':
          description: Bad request
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/Problem'
        '404':
          description: Agreement not found
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/Problem'
  '/eservice/{eserviceId}':
    get:
      tags:
        - api
      summary: Get an eService
      description: Retrieve an eService using an eService identifier
      operationId: getEService
      security:
        - bearerAuth: [ ]
      parameters:
        - name: eserviceId
          in: path
          description: the eservice Id
          required: true
          schema:
            type: string
      responses:
        '200':
          description: EService retrieved
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/EService'
        '400':
          description: Bad request
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/Problem'
        '404':
          description: Agreement not found
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/Problem'
  /agreements:
    get:
      tags:
        - api
      summary: Retrieve a list of agreement
      description: List
      operationId: getAgreements
      parameters:
        - in: query
          name: producerId
          schema:
            type: string
        - in: query
          name: consumerId
          schema:
            type: string
        - in: query
          name: eserviceId
          schema:
            type: string
        - in: query
          name: descriptorId
          schema:
            type: string
        - in: query
          name: state
          schema:
            $ref: '#/components/schemas/AgreementState'
      responses:
        '200':
          description: A list of Agreement
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Agreements'
        '400':
          description: Bad Request
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/Problem'
  /status:
    get:
      summary: Ritorna lo stato dell'applicazione.
      description: |
        Ritorna lo stato dell'applicazione. A scopo
        di test, su base randomica puo' ritornare
        un errore.
      operationId: get_status
      tags:
        - api
      responses:
        '200':
          description: |
            Il server ha ritornato lo status. In caso di problemi
            ritorna sempre un problem+json.
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/Problem'
components:
  schemas:
    Subscriber:
      type: object
      additionalProperties: false
      properties:
        id:
          type: string
          format: uuid
        name:
          type: string
        category:
          type: string
      required:
        - id
        - name
        - category
    EServiceState:
      type: string
      description: EService State
      enum:
        - ACTIVE
        - PENDING
        - SUSPENDED
        - INACTIVE
    EService:
      type: object
      additionalProperties: false
      properties:
        id:
          type: string
          format: uuid
        descriptorId:
          type: string
          format: uuid
        version:
          type: string
          pattern: /^[0-9]+$/
        name:
          type: string
          pattern: /^[a-zA-Z]/s+$/
        state:
          $ref: '#/components/schemas/EServiceState'
      required:
        - id
        - descriptorId
        - version
        - name
        - state
    PurposeState:
      type: string
      description: Purpose State
      enum:
        - ACTIVE
        - PENDING
        - SUSPENDED
        - INACTIVE
    Purpose:
      type: object
      additionalProperties: false
      properties:
        id:
          type: string
          format: uuid
        througput:
          type: integer
          format: int32
        state:
          $ref: '#/components/schemas/PurposeState'
      required:
        - id
        - througput
        - state
    Purposes:
      type: array
      items:
        $ref: '#/components/schemas/Purpose'
    AttributeState:
      type: string
      description: Attribute State
      enum:
        - ACTIVE
        - PENDING
        - SUSPENDED
        - INACTIVE
    Attribute:
      type: object
      additionalProperties: false
      title: VerifiedAttribute
      description: represents the details of a verified attribute bound to the agreement.
      properties:
        id:
          type: string
          format: uuid
        name:
          type: string
          pattern: .*
          maxLength: 48
        state:
          $ref: '#/components/schemas/AttributeState'
      required:
        - id
        - name
        - state
    Attributes:
      type: array
      items:
        $ref: '#/components/schemas/Attribute'
    AgreementState:
      type: string
      description: Agreement State
      enum:
        - ACTIVE
        - PENDING
        - SUSPENDED
        - INACTIVE
    Agreement:
      type: object
      additionalProperties: false
      properties:
        id:
          type: string
          format: uuid
        eserviceId:
          $ref: '#/components/schemas/EService'
        descriptorId:
          type: string
          format: uuid
        producerId:
          $ref: '#/components/schemas/Subscriber'
        consumerId:
          $ref: '#/components/schemas/Subscriber'
        state:
          $ref: '#/components/schemas/AgreementState'
        attributes:
          $ref: '#/components/schemas/Attributes'
        purposes:
          $ref: '#/components/schemas/Purposes'
      required:
        - id
        - eserviceId
        - descriptorId
        - producerId
        - consumerId
        - state
        - attributes
        - purpose
      description: business representation of an agreement
    Agreements:
      type: object
      properties:
        agreements:
          $ref: '#/components/schemas/Agreement'
      required:
        - agreements
    Problem:
      properties:
        type:
          description: URI reference of type definition
          type: string
        status:
          description: The HTTP status code generated by the origin server for this occurrence of the problem.
          example: 503
          exclusiveMaximum: true
          format: int32
          maximum: 600
          minimum: 100
          type: integer
        title:
          description: A short, summary of the problem type. Written in english and readable
          example: Service Unavailable
          maxLength: 64
          pattern: '^[ -~]{0,64}$'
          type: string
        detail:
          description: A human readable explanation of the problem.
          example: Request took too long to complete.
          maxLength: 4096
          pattern: '^.{0,1024}$'
          type: string
        errors:
          type: array
          minItems: 0
          items:
            $ref: '#/components/schemas/ProblemError'
      additionalProperties: false
      required:
        - type
        - status
        - title
        - errors
    ProblemError:
      properties:
        code:
          description: Internal code of the error
          example: 123-4567
          minLength: 8
          maxLength: 8
          pattern: '^[0-9]{3}-[0-9]{4}$'
          type: string
        detail:
          description: A human readable explanation specific to this occurrence of the problem.
          example: Parameter not valid
          maxLength: 4096
          pattern: '^.{0,1024}$'
          type: string
      required:
        - code
        - detail
  securitySchemes:
    bearerAuth:
      type: http
      description: 'A bearer token in the format of a JWS and conformed to the specifications included in [RFC8725](https://tools.ietf.org/html/RFC8725).'
      scheme: bearer
      bearerFormat: JWT d'Interoperabilità di AgID (default)
